resources:
- oauth.yaml
- self-provisioners.yaml
- project-leaders.yaml
secretGenerator:
- name: idp-localusers
  namespace: openshift-config
  files:
  - htpasswd=idp-localusers-data
generatorOptions:
  disableNameSuffixHash: true
